<template>
  <section class="templates section">
    <div class="templates__inner container">
      <div class="templates__top">
        <div class="templates__copy">
          <SectionTitle
            eyebrow="Project templates"
            title="Start from the shape of the project, not from an empty folder."
            description="Vix templates are the starting points generated by vix new. Each template gives the project a different shape depending on what it is meant to become: a small application, a backend service, a server-rendered web app, a Vue frontend with a Vix backend, a game project, or a reusable C++ library."
          />

          <div class="templates__text">
            <p>
              A template is not only a directory layout. It decides which files
              are generated, which workflow is suggested after creation, how
              <code>vix.app</code> or CMake is used, which runtime resources are
              copied, and how the project can grow.
            </p>

            <p>
              Application, backend, web, Vue, and game projects are
              application-oriented. The library template is different: it starts
              from reusable C++ code, public headers, examples, tests, and a
              package-style build shape.
            </p>
          </div>

          <a
            class="templates__link"
            href="https://docs.vixcpp.com/templates/"
            target="_blank"
            rel="noreferrer"
          >
            Read templates docs
            <span aria-hidden="true">→</span>
          </a>
        </div>

        <aside class="templates__panel" aria-label="Vix new workflow">
          <div class="templates__panel-head">
            <p class="templates__label">vix new</p>
            <strong>Choose the project shape before the code grows.</strong>
          </div>

          <div class="templates__commands">
            <CommandLine command="vix new hello --app" />
            <CommandLine command="vix new api --template backend" />
            <CommandLine command="vix new dashboard --template vue" />
            <CommandLine command="vix new mathkit --lib" />
          </div>

          <div class="templates__workflow">
            <p class="templates__workflow-label">Generated workflow</p>

            <div
              v-for="step in workflow"
              :key="step.title"
              class="templates__workflow-row"
            >
              <span aria-hidden="true" />
              <div>
                <strong>{{ step.title }}</strong>
                <p>{{ step.text }}</p>
              </div>
            </div>
          </div>
        </aside>
      </div>

      <div class="templates__grid">
        <a
          v-for="template in templates"
          :key="template.name"
          class="template-card"
          :href="template.href"
          target="_blank"
          rel="noreferrer"
        >
          <span class="template-card__index">{{ template.index }}</span>

          <div>
            <h3>{{ template.name }}</h3>
            <p>{{ template.description }}</p>
          </div>

          <span class="template-card__command">{{ template.command }}</span>

          <span class="template-card__arrow" aria-hidden="true">→</span>
        </a>
      </div>
    </div>
  </section>
</template>

<script setup>
import CommandLine from "@/components/common/CommandLine.vue";
import SectionTitle from "@/components/common/SectionTitle.vue";

const templates = [
  {
    index: "01",
    name: "Application",
    command: "vix new hello --app",
    href: "https://docs.vixcpp.com/templates/application",
    description:
      "A small Vix application with a vix.app manifest, a minimal entry point, tests, and a module registry path for future growth.",
  },
  {
    index: "02",
    name: "Backend",
    command: "vix new api --template backend",
    href: "https://docs.vixcpp.com/templates/backend",
    description:
      "A structured API or backend service with AppBootstrap, route and middleware registries, health routes, runtime resources, and production metadata.",
  },
  {
    index: "03",
    name: "Web",
    command: "vix new site --template web",
    href: "https://docs.vixcpp.com/templates/web",
    description:
      "A server-rendered Vix web app with views, public assets, page controllers, middleware, and browser-facing routes.",
  },
  {
    index: "04",
    name: "Vue",
    command: "vix new dashboard --template vue",
    href: "https://docs.vixcpp.com/templates/vue",
    description:
      "A combined project where Vue owns the frontend under frontend/ and Vix owns the C++ backend and API routes.",
  },
  {
    index: "05",
    name: "Game",
    command: "vix new space-demo --game",
    href: "https://docs.vixcpp.com/templates/game",
    description:
      "A Vix game runtime project with a scene entry point, assets, game.package.json, and links to vix::game and vix::io.",
  },
  {
    index: "06",
    name: "Library",
    command: "vix new mathkit --lib",
    href: "https://docs.vixcpp.com/templates/library",
    description:
      "A reusable C++ library shape with public headers, examples, tests, CMake packaging, and project metadata.",
  },
];

const workflow = [
  {
    title: "Create",
    text: "Generate the project from the template that matches the real direction.",
  },
  {
    title: "Build",
    text: "Use the normal Vix workflow for application templates, or build all targets for libraries.",
  },
  {
    title: "Grow",
    text: "Move from a small app to modules, production files, frontend tasks, assets, or package structure when the project needs it.",
  },
];
</script>

<style scoped>
.templates {
  position: relative;
  overflow: hidden;
}

.templates::before {
  content: "";
  position: absolute;
  inset: 0;
  pointer-events: none;
  background:
    radial-gradient(
      circle at 14% 14%,
      rgba(34, 197, 94, 0.1),
      transparent 28rem
    ),
    radial-gradient(rgba(255, 255, 255, 0.04) 1px, transparent 1px);
  background-size:
    auto,
    24px 24px;
  opacity: 0.42;
  mask-image: linear-gradient(#000, transparent 88%);
}

.templates__inner {
  position: relative;
  display: grid;
  gap: 42px;
}

.templates__top {
  display: grid;
  grid-template-columns: minmax(0, 1.25fr) 430px;
  gap: clamp(36px, 5vw, 72px);
  align-items: start;
}

.templates__copy {
  min-width: 0;
}

.templates__text {
  margin-top: 28px;
  display: grid;
  gap: 18px;
  max-width: 720px;
}

.templates__text p {
  color: var(--text-soft);
  font-size: clamp(1rem, 1.25vw, 1.08rem);
  line-height: 1.82;
}

.templates__text code {
  color: var(--green-bright);
  font-family: var(--font-mono);
  font-size: 0.92em;
}

.templates__link {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  margin-top: 30px;
  color: var(--green-strong);
  font-family: var(--font-mono);
  font-size: 0.9rem;
  font-weight: 650;
  text-decoration: none;
}

.templates__link:hover {
  color: var(--green);
}

.templates__panel {
  position: sticky;
  top: 84px;
  overflow: hidden;
  border: 1px solid rgba(34, 197, 94, 0.16);
  border-radius: var(--radius-lg);
  background: var(--bg-ink);
  box-shadow: var(--shadow-lg);
}

.templates__panel-head {
  padding: 24px 24px 20px;
  border-bottom: 1px solid rgba(34, 197, 94, 0.14);
}

.templates__label {
  margin: 0 0 8px;
  color: var(--green-bright);
  font-family: var(--font-mono);
  font-size: 0.7rem;
  font-weight: 850;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

.templates__panel-head strong {
  display: block;
  color: var(--text);
  font-size: 1.15rem;
  line-height: 1.28;
  letter-spacing: -0.03em;
}

.templates__commands {
  display: grid;
  gap: 8px;
  padding: 22px 24px;
  border-bottom: 1px solid var(--line-soft);
}

.templates__workflow {
  display: grid;
  gap: 14px;
  padding: 22px 24px 24px;
}

.templates__workflow-label {
  margin: 0 0 2px;
  color: var(--text-muted);
  font-family: var(--font-mono);
  font-size: 0.7rem;
  font-weight: 800;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}

.templates__workflow-row {
  display: flex;
  gap: 12px;
  align-items: flex-start;
}

.templates__workflow-row > span {
  width: 7px;
  height: 7px;
  margin-top: 0.45em;
  border-radius: 999px;
  background: var(--green);
  box-shadow: 0 0 0 4px rgba(34, 197, 94, 0.08);
  flex: 0 0 auto;
}

.templates__workflow-row strong {
  display: block;
  color: var(--text);
  font-size: 0.9rem;
  font-weight: 850;
}

.templates__workflow-row p {
  margin-top: 5px;
  color: var(--text-muted);
  font-size: 0.82rem;
  line-height: 1.5;
}

.templates__grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}

.template-card {
  position: relative;
  min-height: 250px;
  display: flex;
  flex-direction: column;
  padding: 22px;
  border: 1px solid var(--line);
  border-radius: var(--radius-lg);
  background: var(--bg-panel);
  box-shadow: var(--shadow-xs);
  transition:
    border-color var(--speed) var(--ease),
    background var(--speed) var(--ease),
    box-shadow var(--speed) var(--ease),
    transform var(--speed) var(--ease);
}

.template-card:hover {
  border-color: var(--green-line);
  background: var(--bg-soft);
  box-shadow: var(--shadow-sm);
  transform: translateY(-2px);
}

.template-card__index {
  display: inline-block;
  width: fit-content;
  color: var(--green-bright);
  font-family: var(--font-mono);
  font-size: 0.72rem;
  font-weight: 850;
  letter-spacing: 0.08em;
}

.template-card h3 {
  margin-top: 18px;
  color: var(--text);
  font-size: 1.08rem;
  font-weight: 850;
  letter-spacing: -0.03em;
}

.template-card p {
  margin-top: 10px;
  color: var(--text-muted);
  font-size: 0.9rem;
  line-height: 1.65;
}

.template-card__command {
  width: fit-content;
  margin-top: auto;
  padding-top: 22px;
  color: var(--green-strong);
  font-family: var(--font-mono);
  font-size: 0.76rem;
  font-weight: 650;
  line-height: 1.5;
}

.template-card__arrow {
  position: absolute;
  right: 22px;
  bottom: 20px;
  color: var(--text-faint);
  font-size: 1.1rem;
  transition:
    color var(--speed) var(--ease),
    transform var(--speed) var(--ease);
}

.template-card:hover .template-card__arrow {
  color: var(--green-strong);
  transform: translateX(4px);
}

@media (max-width: 980px) {
  .templates__top {
    grid-template-columns: 1fr;
  }

  .templates__panel {
    position: relative;
    top: auto;
    max-width: 680px;
  }

  .templates__grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 620px) {
  .templates__grid {
    grid-template-columns: 1fr;
  }

  .templates__panel-head,
  .templates__commands,
  .templates__workflow {
    padding-inline: 20px;
  }

  .template-card {
    min-height: auto;
  }

  .template-card__arrow {
    position: static;
    margin-top: 16px;
  }
}
</style>
